import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { AnalysisHeader } from "@/components/analysis-header";
import { actionLabels, categoryLabels, label, severityLabels } from "@/components/labels";
import { ShareButton } from "@/components/share-button";
import { getDatabase } from "@/db/client";
import { creatorCookieName } from "@/domain/creator-access/cookie";
import { getRunContext, isRunCreator, listRunClusters, listRunIssues } from "@/queries/product";
export const dynamic = "force-dynamic";

export default async function Overview({ params, searchParams }: { params: Promise<{ runId: string }>; searchParams: Promise<Record<string,string | string[] | undefined>> }) {
  const { runId } = await params; const query = await searchParams; const { db } = getDatabase(); const context = await getRunContext(db, runId); if (!context) notFound();
  const creator = await isRunCreator(db, runId, (await cookies()).get(creatorCookieName(runId))?.value); const allIssues = await listRunIssues(db, runId); const clusterRows = await listRunClusters(db, runId);
  const category = single(query.category), severity = single(query.severity), state = single(query.state), action = single(query.action);
  const valid = allIssues.filter((item) => item.effective); const filtered = valid.filter((item) => (!category || item.effective?.category === category) && (!severity || item.effective?.severity === severity) && (!state || item.issue.state === state) && (!action || item.effective?.suggestedAction === action));
  const high = valid.filter((item) => ["high","critical"].includes(item.effective!.severity)).length; const unknown = valid.filter((item) => item.effective!.category === "unknown" || item.effective!.severity === "unknown").length;
  const categories = counts(valid.map((item) => item.effective!.category)); const maxCount = Math.max(1, ...Object.values(categories));
  return <main><AnalysisHeader runId={runId} repository={`${context.repository.owner}/${context.repository.name}`} active="overview" readOnly={!creator}/><div className="dashboard shell">
    {context.run.status === "partial" && <p className="warning">部分 Issue 分析失败；以下统计仅基于 {context.run.succeededCount} 条有效分析。</p>}
    <section className="dashboard-title"><div><p className="eyebrow">Insight overview</p><h1>产品问题全景</h1><p>{context.run.succeededCount} / {context.run.totalCount} 条 Issue 已形成有效分析</p></div><ShareButton/></section>
    <section className="kpi-grid" aria-label="关键指标"><article><span>有效分析</span><strong>{valid.length}</strong><small>失败 {context.run.failedCount}</small></article><article><span>高 / 严重</span><strong>{high}</strong><small>占有效分析 {valid.length ? Math.round(high / valid.length * 100) : 0}%</small></article><article><span>问题簇</span><strong>{clusterRows.length}</strong><small>暂定聚类</small></article><article><span>待判断字段</span><strong>{unknown}</strong><small>建议人工复核</small></article></section>
    <section className="panel"><div className="section-title"><div><p className="eyebrow">Top clusters</p><h2>优先关注的问题簇</h2></div><span className="badge neutral">暂定优先级</span></div>{clusterRows.length ? <div className="cluster-grid">{clusterRows.slice(0,6).map(({ cluster, memberIds }, index) => <a className="cluster-card" href={`/analysis/${runId}/clusters/${cluster.id}`} key={cluster.id}><span className="rank">0{index + 1}</span><h3>{cluster.name}</h3><p>{cluster.summary}</p><footer><strong>{memberIds.length} 条 Issue</strong><span>优先级 {Math.round((cluster.priorityScore ?? 0) * 100)}</span></footer></a>)}</div> : <div className="empty-state"><h3>尚未生成问题簇</h3><p>旧任务或无有效分析时可能出现此状态；单条 Issue 仍可浏览。</p></div>}</section>
    <section className="panel split"><div><div className="section-title"><h2>类别分布</h2></div><div className="bar-chart" aria-label="Issue 类别分布">{Object.entries(categories).map(([key,value]) => <div className="bar-row" key={key}><span>{label(categoryLabels,key)}</span><div><i style={{ width: `${value/maxCount*100}%` }}/></div><strong>{value}</strong></div>)}</div></div><div className="method-note"><p className="eyebrow">How to read</p><h2>数据口径</h2><p>统计只纳入成功或命中缓存的 AI 分析；失败项不进入分布。人工修正后的有效值会替代模型值参与筛选。</p></div></section>
    <section className="panel" id="issues"><div className="section-title"><div><p className="eyebrow">Evidence table</p><h2>逐条查看 Issue</h2></div><span>{filtered.length} 条结果</span></div><form className="filters" method="get"><label>类别<select name="category" defaultValue={category}><option value="">全部</option>{Object.entries(categoryLabels).map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></label><label>严重性<select name="severity" defaultValue={severity}><option value="">全部</option>{Object.entries(severityLabels).map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></label><label>GitHub 状态<select name="state" defaultValue={state}><option value="">全部</option><option value="open">Open</option><option value="closed">Closed</option></select></label><label>建议动作<select name="action" defaultValue={action}><option value="">全部</option>{Object.entries(actionLabels).map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></label><button className="secondary">应用筛选</button><a className="text-link" href={`/analysis/${runId}/overview#issues`}>清除</a></form>{filtered.length ? <div className="issue-table"><div className="table-head"><span>Issue</span><span>类别</span><span>严重性</span><span>产品区域</span><span>状态</span></div>{filtered.map((item) => <a className="table-row" href={`/analysis/${runId}/issues/${item.runIssue.id}`} key={item.runIssue.id}><span><strong>#{item.issue.issueNumber} {item.issue.title}</strong><small>{item.effective!.summary}</small></span><span>{label(categoryLabels,item.effective!.category)}</span><span><i className={`severity ${item.effective!.severity}`}>{label(severityLabels,item.effective!.severity)}</i></span><span>{item.effective!.productArea}</span><span>{item.issue.state === "open" ? "Open" : "Closed"}</span></a>)}</div> : <div className="empty-state"><h3>没有符合条件的 Issue</h3><p>调整或清除筛选条件后再试。</p></div>}</section>
  </div></main>;
}
function single(value: string | string[] | undefined) { return typeof value === "string" ? value : ""; }
function counts(values: string[]) { return values.reduce<Record<string,number>>((result,value) => { result[value] = (result[value] ?? 0) + 1; return result; }, {}); }
