"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { categoryLabels, severityLabels } from "@/components/labels";

export function CorrectionForm({ runId, runIssueId, current, clusters }: { runId: string; runIssueId: string; current: { category: string; severity: string; productArea: string; targetClusterId?: string | null }; clusters: { id: string; name: string }[] }) {
  const router = useRouter(); const dialog = useRef<HTMLDialogElement>(null); const [error,setError] = useState(""); const [saving,setSaving] = useState(false);
  useEffect(() => { const node=dialog.current; const close=()=>setError(""); node?.addEventListener("close",close); return()=>node?.removeEventListener("close",close); },[]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const data=new FormData(event.currentTarget); const body={ category:data.get("category"), severity:data.get("severity"), productArea:data.get("productArea"), targetClusterId:data.get("targetClusterId") || undefined }; try { const response=await fetch(`/api/analysis/${runId}/issues/${runIssueId}/corrections`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error?.message??"保存失败"); dialog.current?.close(); router.refresh(); } catch(cause){setError(cause instanceof Error?cause.message:"保存失败");} finally{setSaving(false);} }
  return <><button className="secondary" onClick={()=>dialog.current?.showModal()}>修正 AI 判断</button><dialog className="correction-dialog" ref={dialog} aria-labelledby="correction-title"><form onSubmit={submit}><div className="dialog-head"><div><p className="eyebrow">Human correction</p><h2 id="correction-title">修正结构化字段</h2></div><button className="icon-button" type="button" onClick={()=>dialog.current?.close()} aria-label="关闭">×</button></div><p className="help">修正会作为新记录保存，不覆盖原始模型输出。</p><label>类别<select name="category" defaultValue={current.category}>{Object.entries(categoryLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>严重性<select name="severity" defaultValue={current.severity}>{Object.entries(severityLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>产品区域<input name="productArea" defaultValue={current.productArea} required maxLength={80}/></label><label>归属问题簇<select name="targetClusterId" defaultValue={current.targetClusterId??""}><option value="">保持当前归属</option>{clusters.map((cluster)=><option value={cluster.id} key={cluster.id}>{cluster.name}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>dialog.current?.close()}>取消</button><button className="primary" disabled={saving}>{saving?"保存中…":"保存修正"}</button></div></form></dialog></>;
}
