"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Route } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter(); const [repository, setRepository] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const hydrated=false; useEffect(()=>{document.querySelector("form.repo-form")?.setAttribute("data-hydrated","true");},[]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); try { const response = await fetch("/api/repositories/validate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ repository }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "无法验证仓库"); router.push(`/analysis/new?repository=${encodeURIComponent(payload.data.repository.slug)}` as Route); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法验证仓库"); } finally { setLoading(false); } }
  return <main><header className="site-header"><Link className="brand" href="/">IssueLens</Link><span className="header-note">GitHub Issue → 产品洞察</span></header><section className="hero shell"><div><p className="eyebrow">Evidence-first product intelligence</p><h1>从一堆 Issue，看到真正该解决的问题。</h1><p className="lead">输入一个公开 GitHub 仓库。IssueLens 会读取最近更新的 100 条 Issue，用 AI 提炼主题、严重性和行动建议，并让每条结论都能回到原始证据。</p></div><form className="repo-form" action="/analysis/new" method="get" onSubmit={submit} aria-label="创建仓库分析" data-hydrated={hydrated}><label htmlFor="repository">公开仓库地址</label><div className="input-row"><input id="repository" name="repository" value={repository} onChange={(e) => setRepository(e.target.value)} placeholder="github.com/owner/repo 或 owner/repo" required aria-describedby="repo-help repo-error"/><button disabled={loading}>{loading ? "正在验证…" : "开始分析"}</button></div><p id="repo-help" className="help">只读访问，不需要 GitHub 登录，不读取评论正文。</p>{error && <p id="repo-error" className="error" role="alert">{error}</p>}</form></section><section className="feature-grid shell" aria-label="产品特点"><article><span>01</span><h2>结构化</h2><p>类别、严重性、产品区域和行动建议采用稳定字段，便于筛选与复核。</p></article><article><span>02</span><h2>可追溯</h2><p>摘要旁保留原始标题、正文、标签和 GitHub 链接，不把 AI 猜测包装成事实。</p></article><article><span>03</span><h2>可修正</h2><p>任务创建者可覆盖关键判断；分享给同事时默认只读，不泄露权限凭证。</p></article></section></main>;
}
