import { describe,expect,it,vi } from "vitest";
import { OpenAIClusterClient,ClusterProviderError } from "./openai-cluster-client";
const a="11111111-1111-4111-8111-111111111111",b="22222222-2222-4222-8222-222222222222";
const items=[a,b].map((runIssueId,index)=>({runIssueId,issueNumber:index+1,title:`Error ${index}`,commentsCount:1,updatedAt:"2026-08-21T00:00:00.000Z",analysis:{category:"bug" as const,summary:"Error response shape is inconsistent.",productArea:"Node client",userScenario:"Handle API errors",severity:"medium" as const,suggestedAction:"product" as const}}));
function ok(body:unknown){return new Response(JSON.stringify({id:"resp_cluster",output_text:JSON.stringify(body),usage:{input_tokens:120,output_tokens:50}}),{status:200,headers:{"x-request-id":"req_cluster"}});}
describe("OpenAIClusterClient",()=>{
  it("requests strict structured output and validates membership",async()=>{const request=vi.fn().mockResolvedValue(ok({clusters:[{name:"Node 错误响应",summary:"两条 Issue 都涉及错误响应结构。",suggestedAction:"product",memberRunIssueIds:[a,b]}],unclusteredRunIssueIds:[]}));const client=new OpenAIClusterClient({apiKey:"test",fetch:request,maxAttempts:1});const result=await client.cluster(items);expect(result.plan.clusters[0]?.memberRunIssueIds).toEqual([a,b]);const sent=JSON.parse(request.mock.calls[0]![1].body);expect(sent.store).toBe(false);expect(sent.text.format).toMatchObject({type:"json_schema",strict:true});});
  it("repairs duplicate membership without losing billed usage",async()=>{const request=vi.fn().mockResolvedValue(ok({clusters:[{name:"Node 错误响应",summary:"相关",suggestedAction:"product",memberRunIssueIds:[a,b]}],unclusteredRunIssueIds:[b]}));const client=new OpenAIClusterClient({apiKey:"test",fetch:request,maxAttempts:1});await expect(client.cluster(items)).resolves.toMatchObject({plan:{clusters:[{memberRunIssueIds:[a,b]}],unclusteredRunIssueIds:[]},providerRequestId:"req_cluster",inputTokens:120,outputTokens:50});});
  it("maps quota exhaustion without retry",async()=>{const request=vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{type:"insufficient_quota"}}),{status:429}));const client=new OpenAIClusterClient({apiKey:"test",fetch:request,maxAttempts:3,sleep:vi.fn()});await expect(client.cluster(items)).rejects.toEqual(new ClusterProviderError("CLUSTER_QUOTA_EXHAUSTED",false,429));expect(request).toHaveBeenCalledTimes(1);});
});
